### ISSUE TITLE
EmployerId

### ISSUE THREAD

**Issue by pvdbosch** [belgif/openapi-employment-identifier#1]
validate EmployerId (v1beta) and promote it.

Still need for separate Ids for provisional, nsso, provincialOrLocal? 
Validate schema file structure change ("employment/identifier/v1"; formerly under nsso). 

Also depends on integer vs string (https://github.com/belgif/rest-guide/issues/60)

**Comment by smals-chlo** [comment]
Hi @pvdbosch , 

I cannot find any common schema for enterpriseNumber. Is there a reason for this? Is it hidden somewhere? 

Both enterpriseNumber and employerId are included in the Federal Service Platform Vocabulary file, with inSwagger = Yes. 

![enterpriseNumber](https://user-images.githubusercontent.com/59614111/102475067-b0f44e80-4059-11eb-9710-2a32631ab8ba.PNG)

**Comment by pvdbosch** [comment]
Hi @smals-chlo , you can find the enterpriseNumber in the organization identifier repo: https://github.com/belgif/openapi-organization-identifier/blob/master/src/main/swagger/organization/identifier/v1/organization-identifier-v1.yaml

Not all organizations (with a CBE number) are employers. Employer schemas are more related to the NSSO-domain.

**Comment by smals-chlo** [comment]
Thanks @pvdbosch , 
Is there a reason that the organization identifier repo (https://github.com/belgif/openapi-organization-identifier/blob/master/src/main/swagger/organization/identifier/v1/organization-identifier-v1.yaml)  is not published in the open-api schema's? https://github.com/orgs/belgif/projects/1

**Comment by pvdbosch** [comment]
https://github.com/orgs/belgif/projects/1 is an issue board for all open issues in openapi-* repos. There are no open issues in organization-identifier.

organization-identifier is part of the list on https://github.com/belgif/rest-guide (README.md on main page), and published on maven central: https://search.maven.org/search?q=g:io.github.belgif.openapi

**Comment by smals-chlo** [comment]
OK thanks, clear now.

**Comment by pvdbosch** [comment]
Breakdown of the employer ids, since the DUNIA project at NSSO:
* the ones starting with 51 + 8 digits are provisional identifiers
* the ones with 9 digits are 'normal' employer identifiers
* the ones with length 5 digits are old identifiers for provincial or local authorities. They may still be used for historical data; but are replaced with 9 digit long ones for new and recent data.

The proposed EmployerId type doesn't make this distinction; so it allows further evolution of the EmployerId.
It only has minimum 0 and max 5 999 999 999. Is this too restrictive (we could set max to 9 999 999 999) or too lenient (we could set a higher minimum and restrict max to 5 199 999 999)?

**Comment by pvdbosch** [comment]
validated by technical WG

**Comment by pvdbosch** [comment]
added fedvoc reference in comments, ready for final review in next functional WG

**Comment by pvdbosch** [comment]
validated on functional WG. Can be published. Already marked as "inSwagger" in the excel sheet.

**Comment by pvdbosch** [comment]
I created a [v1.0.1](https://github.com/belgif/openapi-employment-identifier/releases/tag/v1.0.1) release. The v1.0.0 release had no yaml files and shouldn't be used.

It will also be available in Maven Central after next update of its index.
